remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-architect
title: Alien Invasion
description: 
show_downloads: ["true"]
github:
  download_release: https://github.com/ShubhamMaht0/Alien_Invasion/zipball/main
  owner_url: https://github.com/ShubhamMaht0
